### ISSUE TITLE
Implement list based search

### ISSUE THREAD

**Issue by ingenieroariel** [boundlessgeo/exchange-search#1]
![mockup-search-02](https://cloud.githubusercontent.com/assets/54999/14796914/762d7248-0af5-11e6-9eca-107f2c7da73a.png)

 - [ ]  Styling
 - [ ]  Code Styles
 - [ ] Use the selected map
 - [ ] Update the other fields for preview

With title, date and domain in as columns. Things like owner, rating, region will be addressed in a different ticket.

**Comment by ingenieroariel** [comment]
@milafrerichs did the functional part, I am now assigning @lasdjs to take care of the styling part.

@gsolat Can you paste the latest mockup here?

**Comment by gsolat** [comment]
The lastest mockup in order to maintain the style close to the actual look of the search

![mockup-search-05](https://cloud.githubusercontent.com/assets/5114135/14866062/4de58e4a-0c87-11e6-86a0-13315ffc83f1.png)

**Comment by ingenieroariel** [comment]
Just the catalog bit is missing in this one but I will ticket it separately. Good enough to close.
