### ISSUE TITLE
Set up MapLoom search modal based on mockup

### ISSUE THREAD

**Issue by ingenieroariel** [boundlessgeo/exchange-search#12]
![mockup-search-04](https://cloud.githubusercontent.com/assets/54999/14834804/fcad178e-0bcb-11e6-9ca0-2bc7d647ee24.png)

**Comment by ingenieroariel** [comment]
@gsolat, let's  change the 'Map' action to 'Add'

**Comment by gsolat** [comment]
@ingenieroariel Done.

![mockup-search-04](https://cloud.githubusercontent.com/assets/5114135/14836966/fd08dd40-0bd9-11e6-9069-cabec6204e09.png)

**Comment by ingenieroariel** [comment]
Let's merge this with @milafrerichs latest changes and then close

**Comment by ingenieroariel** [comment]
Thanks @milafrerichs and @lasdjs
