### ISSUE TITLE
Mockups for presentation

### ISSUE THREAD

**Issue by ingenieroariel** [boundlessgeo/exchange-search#16]
@gsolat We need two mockups:

 - [x] One with the minimal functionality based on what we can achieve this week
 - [x] One with the full functionality for the next milestone (including date search, cart, etc)

**Comment by gsolat** [comment]
Minimal functionality 
![mockup-search-05](https://cloud.githubusercontent.com/assets/5114135/14870827/a946b8ca-0ca2-11e6-9345-d1361fe7eb4a.png)

Full functionality
![mockup-search-07](https://cloud.githubusercontent.com/assets/5114135/14870816/90a466aa-0ca2-11e6-94d6-31e7ee2591e9.png)
