### ISSUE TITLE
Add to cart functionality

### ISSUE THREAD

**Issue by ingenieroariel** [boundlessgeo/exchange-search#18]
We need to be able to add layers to a cart before adding them to the main map. This is mainly to support different searches where the list changes but it is not possible to see again the list that the person was looking at before.

![90a466aa-0ca2-11e6-94d6-31e7ee2591e9](https://cloud.githubusercontent.com/assets/54999/14958430/651ff11e-1050-11e6-9690-e6bb27f201f1.png)

**Comment by milafrerichs** [comment]
this can be closed if you satisfied. @ingenieroariel

**Comment by ingenieroariel** [comment]
:+1:
