### ISSUE TITLE
Support date based search

### ISSUE THREAD

**Issue by ingenieroariel** [boundlessgeo/exchange-search#19]
This involves:
 - [x] Implementing date filtering in the UI
 - [x] Verifying that the backed is indexing dates correctly.

Assigning to @lasdjs for the first part.

**Comment by lasdjs** [comment]
Hi @ingenieroariel the first checkbox is about this issue? https://github.com/boundlessgeo/exchange-search/issues/28

**Comment by Lenninlasd** [comment]
Hi @ingenieroariel, searching in the database, I can't find a `date` field indexed.
Also searched fields `Date`, `dates`, `Dates`, `Year`, `year`, `Years`, `years`, `day`, `Day` (s).

Query:
```json
curl -XGET 'http://geoshape.geointservices.io/search/hypermap/_search?pretty' -d '
{
  "query": {
    "filtered": {
      "filter": {
        "bool": {
          "must": [
            {
              "exists": {
                "field": "Date"
              }
            }
          ]
        }
      }
    }
  }
}'
```
