### ISSUE TITLE
Ability to select the catalog in the UI

### ISSUE THREAD

**Issue by ingenieroariel** [boundlessgeo/exchange-search#20]
We need to be able to search against more than one catalog. In the mockups there is a dropdown but we need to find a way to fill the information in that dropdown. For now we can hardcode them in the javascript and work on the selection UI.

![90a466aa-0ca2-11e6-94d6-31e7ee2591e9](https://cloud.githubusercontent.com/assets/54999/14958592/1dab2122-1051-11e6-8514-c5b008669039.png)

**Comment by milafrerichs** [comment]
Can you provide a bit more details for the catalogs?

**Comment by Lenninlasd** [comment]
@ingenieroariel the idea is simulate two different catalogs but with the same URL?

**Comment by ingenieroariel** [comment]
Yes, these catalogs would be different instances of the same backend app.
But so far we only have one instance that you can develop against. In order
to overcome this limitation, you can create two different catalogs that are
hitting the same backend to demonstrate the ability to 'reset' the whole
app and look at that other catalog.

In a couple of days I will be sharing a new endpoint that we are going to
use going forward but for now it is okay to use the same URL twice with
different names.

**Comment by Lenninlasd** [comment]
An additional question, with a new endpoind changes the whole URL, or only **HyperMap** front part of this link? http://geoshape.geointservices.io/search/hypermap/

**Comment by ingenieroariel** [comment]
On Mon, May 16, 2016 at 3:31 PM, Lennin Suescun <notifications@github.com>
wrote:

> http://geoshape.geointservices.io/search/hypermap/
>

The whole URL would change.
