### ISSUE TITLE
Time scale

### ISSUE THREAD

**Issue by gsolat** [boundlessgeo/exchange-search#28]
This time scale could be more useful than current one.

`5000M BC
500M BC
50M BC
5M BC
1M BC
100K BC
10K BC
1K BC
500 BC
100 BC
0
100
500
1000
1500
1600
1700
1800
1900
1910
1920
1930
1940
1950
1960
1970
1980
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2050
2100
Future 
`

<img width="501" alt="screen shot 2016-05-10 at 11 12 53 am" src="https://cloud.githubusercontent.com/assets/5114135/15155257/4bb17722-16a7-11e6-8e25-998e57ee3719.png">

**Comment by lasdjs** [comment]
That is the exact range that should be or is an example?

**Comment by gsolat** [comment]
That's the exact range.

**Comment by lasdjs** [comment]
What is the default range of the slider? 1500 - 2016?

**Comment by gsolat** [comment]
5000 M BC - Future
